### ISSUE TITLE
POA fails when WindowsUpdate registry key is missing

### ISSUE THREAD

**Issue by tastyeggs** [microsoft/Service-Fabric-POA#30]
On some windows server (fresh) installs, the following registry key is missing:

HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU

This missing registry key appears to be a widespread issue. Incidentally on these machines, Windows Update appears to be by default configured to auto-download and install.

This then causes WindowsAutoUpdateUtility\LogCurrentAUValues to crash with a NullReferenceException on line 43, as `auKey` is null.

I've fixed this in my cluster by rolling out a Group Policy forcing Automatic Updates to "2 - Notify Download and Install", which subsequently creates the above registry key.

This could also be fixed if the POA creates the "WindowsUpdate\AU" subkeys under "HKLM\SOFTWARE\Policies\Microsoft\Windows".

At the very least, if the key is not expected to exist unless Windows Update is manually configured, the error message should be helpful, as opposed to crashing on a Null Reference Exception.

**Comment by khandelwalbrijesh** [comment]
@tastyeggs 
Thanks for reporting this!!
We take this issue in next release of POA. We will throw a more helpful message to the user in this case.

**Comment by saketharsh** [comment]
v1.4.5 contains a fix for this issue where POA creates the registry when it is missing.

**Comment by VikSarMS** [comment]
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
is missing in registry

wireless display feature was not installing in my win 11
