### ISSUE TITLE
Number of health reports on NodeAgentService goes above MaxSuggestedNumberOfEntityHealthReports when number of nodes are more than MaxSuggestedNumberOfEntityHealthReports/2.

### ISSUE THREAD

**Issue by khandelwalbrijesh** [microsoft/Service-Fabric-POA#33]
Maximum number of health reports on an entity can only be 500. If there are reports more than that for a single health entity a warning is posted on that entity. This does not impact the functioning of POA but it will be stay in warning state all the time.

MaxSuggestedNumberOfEntityHealthReports has default value of 500.

![image](https://user-images.githubusercontent.com/20697039/63786825-6d2f8000-c910-11e9-9443-19933c4969be.png)

**Comment by khandelwalbrijesh** [comment]
Quick mitigation for this issue would be to increase the MaxSuggestedNumberOfEntityHealthReports to more than twice the number of nodes.

**Comment by milope** [comment]
Hello Team,

Wanted to check if there are plan on expiring this health report to avoid this scenario all together?

**Comment by saketharsh** [comment]
Latest POAv1.4.8 introduces finite TTL to the Health Reports from POA, which would make Health reports from unavailable Nodes/Services go away in a finite time.
