### ISSUE TITLE
Patch Orchestration Application (POA) does not install updates in gMSA security cluster

### ISSUE THREAD

**Issue by vdvarlamov** [microsoft/Service-Fabric-POA#34]
I have standalone cluster 6.5.664.9590 on Windows Server 2019 with gMSA security.
Successfully deployed Patch Orchestration Application (POA) v1.4.1.
In GPO set "Notify to download updates".
POA successfully find and download updates, but does not install updates. The Node Agent NTService does not creates repair tasks for installing updates on the nodes. 
Get-ServiceFabricRepairTask empty.
every ~3 minutes in System log: "The Windows Modules Installer service entered the running state." after a few seconds "The Windows Modules Installer service entered the stopped state."
![Scr_1](https://user-images.githubusercontent.com/47747798/66315438-7b64b900-e91e-11e9-9061-e80cfdeb5aee.PNG)
![Scr_2](https://user-images.githubusercontent.com/47747798/66315547-b2d36580-e91e-11e9-9a32-5771f4f5f749.PNG)
In unsecure dev cluster POA works good.

**Comment by MicahMcKittrick-MSFT** [comment]
@raunakpandya can you help on this? 

@vdvarlamov and I have worked a bit on the same issue in MSDN

https://social.msdn.microsoft.com/Forums/en-US/b07f9b0a-892d-42c1-b9a0-c6212b51c4a2/patch-orchestration-application-poa-does-not-install-updates-in-gmsa-security-cluster?forum=AzureServiceFabric

However it appears he has everything setup correctly but for some reason POA is not finding the updates. We even logged into the node and checked and there are updates available. 

CC @masnider @peterpogorski if you know anyone else who might be able to help.

**Comment by jakaruna-MSFT** [comment]
@masnider Please add your comments

**Comment by khandelwalbrijesh** [comment]
@vdvarlamov  Sorry for late reply. We missed this because of vacations and other commitments.
Regarding problem explained in first comment, POA is able to download the updates but not able to install. Which version of POA are you using? I do not see any reason why POA will not install updates. Could you share the log details for us to confirm this?

Regarding 2nd comment, Is 'InstallWindowsOSOnlyUpdates' parameter set to true? If not, could you share logs for this as well?

**Comment by vdvarlamov** [comment]
Patch Orchestration Application (POA) v1.4.1.
<Parameter Name="InstallWindowsOSOnlyUpdates" Value="false"/>
Which log is of interest?
More information here: https://social.msdn.microsoft.com/Forums/en-US/b07f9b0a-892d-42c1-b9a0-c6212b51c4a2/patch-orchestration-application-poa-does-not-install-updates-in-gmsa-security-cluster?forum=AzureServiceFabric

**Comment by khandelwalbrijesh** [comment]
@vdvarlamov, we need service fabric logs of these clusters. You can collect and share those logs via a blob share or file share.

**Comment by vdvarlamov** [comment]
@khandelwalbrijesh , Log file link: https://drive.google.com/file/d/10dNQSZjvZmHKcSMqzksD3VK9MCTlFh-L/view?usp=sharing

**Comment by vdvarlamov** [comment]
In ETW log, i see next:
{

  "ProviderName": "POA-NodeAgentSFUtility",
  "Id": 2,
  "Message": "RepairManagerHelper.CreateRepairTaskForNode failed. Exception details System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
       at System.Fabric.Interop.NativeClient.IFabricRepairManagementClient2.EndCreateRepairTask(IFabricAsyncOperationContext context)
       at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.ServiceFabric.PatchOrchestration.NodeAgentSFUtility.Helpers.RepairManagerHelper.<CreateRepairTaskForNode>d__6.MoveNext() in D:\a\1\s\src\PatchOrchestrationApplication\NodeAgentSFUtility\src\Helpers\RepairManagerHelper.cs:line 170",
  "ProcessId": 9876,
  "Level": "Error",
  "Keywords": "0x0000F00000000000",
  "EventName": "ErrorMessage",
  "ActivityID": null,
  "RelatedActivityID": null,
  "Payload": {
    "message": "RepairManagerHelper.CreateRepairTaskForNode failed. Exception details System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
         at System.Fabric.Interop.NativeClient.IFabricRepairManagementClient2.EndCreateRepairTask(IFabricAsyncOperationContext context)
         at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.ServiceFabric.PatchOrchestration.NodeAgentSFUtility.Helpers.RepairManagerHelper.<CreateRepairTaskForNode>d__6.MoveNext() in D:\a\1\s\src\PatchOrchestrationApplication\NodeAgentSFUtility\src\Helpers\RepairManagerHelper.cs:line 170"
  }
}

I ran POA as Service Fabric Administrator, https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-run-service-as-ad-user-or-group, but it did not help.

**Comment by vdvarlamov** [comment]
If in service POSNodeSvc(NodeAgentNTService) change manually Log on as ServiceFabricAdmin domain account, then all working. But over time service again Log on as Local System account and error above will appear again. How run POSNodeSvc(NodeAgentNTService) as ServiceFabricAdmin account always?

**Comment by athinanthny** [comment]
@Khandelwalbrijesh please can you address this issue

**Comment by khandelwalbrijesh** [comment]
Have you done this extra step?
You'd have to do an additional step of configuring your windows security(https://docs.microsoft.com/azure/service-fabric/service-fabric-windows-cluster-windows-security#configure-windows-security-using-gmsa)

Add below section in your clustermanifest.
"ClientIdentities": [
{
"Identity": "NT AUTHORITY\SYSTEM",
"IsAdmin": true
}
]

This would whitelist process running as system to access service fabric client api's.
I think this info is missing in the documentation, and we'll have to update the same.

**Comment by khandelwalbrijesh** [comment]
@vdvarlamov  Did you try the above mentioned solution for this issue?

**Comment by vdvarlamov** [comment]
I will try in the near future.

**Comment by vdvarlamov** [comment]
The solution above helped solve the problem. Thanks!
