### ISSUE TITLE
Add ability to space out the update timing for services with long startup time.

### ISSUE THREAD

**Issue by yossistarz** [microsoft/Service-Fabric-POA#37]
When POA starts the update sequence for the nodes, it don’t take into consideration the time it takes to the
service to become “ready to serve requests”. For long updates which take a long time, it might be ok.
But for very quick updates which requires a restart, this might cause the entire cluster to become nonfictional.
 
Right after the restart of a node, and after completing the updates and without waiting for the service to be available and ready to serve, the next node (which might contain the same service) will start the update and restart. 
This means that lease services will be up and ready to serve requests and this number will keep growing as long as the time to update and restart is smaller than the time the service needs to load it’s data into cache and becoming ready to serve.
This will cause a big lose in compute power and for services with very high RPS rate this is a big problem.
 
Adding a setting for minimum time between node updates will solve this issue.
This will allow us to configure the POA with constant timespan which POA will wait between the last Completed Repair task
and the next Repair task that needs to be approved.
 
In case it is acceptable, I can add this functionality and create a PR.

**Comment by yosal** [comment]
I have add a PR to solve this issue
#39

**Comment by khandelwalbrijesh** [comment]
The changes are in master. Closing this issue.

**Comment by yossistarz** [comment]
> The changes are in master. Closing this issue.

It seems that the PR that was referenced here is not merged (it's still Open).
Am i missing something? 😅
