### ISSUE TITLE
TimeManager.cs uses non-FIPS approved MD5 algorithm.

### ISSUE THREAD

**Issue by milope** [microsoft/Service-Fabric-POA#42]
The MD5 algorithm used in TimeManager.cs is not FIPS-approved and will throw cryptograpic exceptions on FIPS mode enabled clusters (see below).

https://github.com/microsoft/Service-Fabric-POA/blob/c283f9be660b4d1fa939ce29032ebc69f9e7fd8a/src/PatchOrchestrationApplication/NodeAgentNTService/src/Manager/TimerManager.cs#L506

I've seen the Azure Storage SDK use a native MD5 implementation to help with this issue:

https://github.com/Azure/azure-storage-net/blob/4bd9460e0b9b007bdb34eaa1329de2257f7a34dc/Lib/ClassLibraryCommon/Core/Util/NativeMD5.cs

**Comment by saketharsh** [comment]
https://github.com/microsoft/Service-Fabric-POA/pull/55

This fixes the issues
