### ISSUE TITLE
Patching issue with 1.4.1

### ISSUE THREAD

**Issue by EinarasTU** [microsoft/Service-Fabric-POA#47]
Hi,
If Azure Fabric Cluster is unhealthy due to some application being in error state cluster halt patching,  but when error is fixed cluster does patching immediately. Is it possible to define maintenance window for example 0100 - 0400 weekly or daily? And if out of that window patching will not be conducted until next window. This is for monthly windows updates, not the cluster image swap.
Thanks!

**Comment by khandelwalbrijesh** [comment]
Patching should start immediately if it got stuck in the middle of the patching cycle. This feature is not supported in POA.
