### ISSUE TITLE
CoordinatorService crash if no completed repair tasks

### ISSUE THREAD

**Issue by dapathy** [microsoft/Service-Fabric-POA#49]
on version 1.4.2

If there are no completed repair tasks and approval policy is set to NodeWise, The Coordinator service will crash on startup.

Aggregate will throw with "System.InvalidOperationException: Sequence contains no elements"

[https://github.com/microsoft/Service-Fabric-POA/blob/c484ed5ae6b03f5e9f791baa21b9b25948c49e96/src/PatchOrchestrationApplication/CoordinatorService/src/RepairManagerHelper.cs#L556](https://github.com/microsoft/Service-Fabric-POA/blob/c484ed5ae6b03f5e9f791baa21b9b25948c49e96/src/PatchOrchestrationApplication/CoordinatorService/src/RepairManagerHelper.cs#L556)

**Comment by khandelwalbrijesh** [comment]
@dapathy Thanks a lot for fixing it and creating the PR. 
I had already tested and made the required changes in my PR and since, my PR as version update changes as well so, keeping it. We are in process of releasing the fix for this.

**Comment by dapathy** [comment]
@khandelwalbrijesh Thank you for the quick release.
