### ISSUE TITLE
Cannot register PatchOrchestrationApplication_v1.4.5.sfpkg with SF Cluster - invalid path

### ISSUE THREAD

**Issue by Jaans** [microsoft/Service-Fabric-POA#65]
The .sfpkg file from the `1.4.5 Release` is adding a sub-folder called "**PatchOrchestrationApplication**" that prevents SF from registering the .sfpkg because it cannot find the ApplicationManifest.xml:

```
The Application Manifest file 'POA\ApplicationManifest.xml' is not found in the store.
```

Upon inspecting the package and comparing to the previous version v1.4.3 that did work, it seems that the latest version added a subfolder that shouldn't be there:
![image](https://user-images.githubusercontent.com/3510981/82978469-fb639e80-a027-11ea-84df-5b9dd3adfa23.png)

It is looking for the ApplicationManifest.xml file to be at the \POA\ApplicationManifest.xml path instead.

Reference: [v1.4.5.sfpkg release](https://github.com/microsoft/Service-Fabric-POA/releases/download/v1.4.5/PatchOrchestrationApplication_v1.4.5.sfpkg)

**Comment by chrudrap** [comment]
I am seeing the same issue. This used to work with 1.4.5, but it has been recently broken as it has an additional folder of PatchOrchestrationApplication as mentioned by Jaans.

**Comment by saketharsh** [comment]
Issue resolved. Github Release for v1.4.5 now contains correct sfpkg file
