### ISSUE TITLE
v1.4.6 release sfpkg is failing to deploy

### ISSUE THREAD

**Issue by rootik** [microsoft/Service-Fabric-POA#73]
Azure Service Fabric version: 7.1.458.9590
OS: Windows Server 2016 Datacenter
OS version: 10.0.14393
POA version: 1.4.6

CoordinatorService.exe and NodeAgentNTService.exe are crashing with unhandled exception.

From Application event log:

**.NET Runtime:**

`Application: CoordinatorService.exe`
`Framework Version: v4.0.30319`
`Description: The process was terminated due to an unhandled exception.`
`Exception Info: exception code e0434352, exception address 00007FFD60DF4F38`
`Stack:`

`Application: NodeAgentNTService.exe`
`Framework Version: v4.0.30319`
`Description: The process was terminated due to an unhandled exception.`
`Exception Info: exception code e0434352, exception address 00007FFD60DF4F38`
`Stack:`

**Application Error**
`Faulting application name: NodeAgentNTService.exe, version: 0.0.0.0, time stamp: 0x5f718322`
`Faulting module name: KERNELBASE.dll, version: 10.0.14393.3659, time stamp: 0x5e9140ed`
`Exception code: 0xe0434352`
`Fault offset: 0x0000000000034f38`
`Faulting process id: 0x4520`
`Faulting application start time: 0x01d69b012ccc90ed`
`Faulting application path: C:\PatchOrchestrationApplication\NodeAgentNTService\NodeAgentNTService.exe`
`Faulting module path: C:\windows\System32\KERNELBASE.dll`
`Report Id: c441e4c2-1431-4233-a9ac-c624697177fc`
`Faulting package full name: `
`Faulting package-relative application ID: `

POA version 1.4.5 works just fine

**Comment by rootik** [comment]
Well, it looks like it is failing on strong name validation.
Tried to execute it from command line:

```
D:\SvcFab\_App\PatchOrchestrationApplicationType_App80\CoordinatorServicePkg.Code.1.4.6>.\CoordinatorService.exe

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'CoordinatorService, Version=0.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
   --- End of inner exception stack trace ---
```

When I disabled the strong name validation on one of SF nodes, it was able to start on that node.
`reg ADD "HKLM\Software\Microsoft\StrongName\Verification\*,*" /f`

![image](https://user-images.githubusercontent.com/13675167/95088570-07204980-071b-11eb-916e-0476b0c61366.png)

**Comment by saketharsh** [comment]
Thanks for the information. Indeed I have verified and its the issue of Strong Name validation. I will fix this and create a new release in next few days

**Comment by saketharsh** [comment]
@rootik  I have created a new release for POA   https://github.com/microsoft/Service-Fabric-POA/releases/tag/v1.4.7

You can try upgrading to this version and let us know if everything works fine.

**Comment by rootik** [comment]
Hey @saketharsh 

It seems, you've fixed the issue.
Both services are healthy now. Tested on a few SF clusters.
You can go ahead and close the ticket.

Good job 👍 
Thanks a mil 

![image](https://user-images.githubusercontent.com/13675167/95179399-79933700-07b8-11eb-9a79-e8ff75672b81.png)
