### ISSUE TITLE
WUFrequency - Week, Day, HH:MM:SS not working (v1.4.9)

### ISSUE THREAD

**Issue by rajakumarbabu** [microsoft/Service-Fabric-POA#79]
Hi,

Recently I have installed PoA v1.4.9 and configured "**WUFrequency - for the week of every month**" as per [document](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-patch-orchestration-application#configure-poa-behavior)

`<Parameter Name="WUFrequency" DefaultValue="3,Sunday,5:00:00" />`

Based on the above parameter, PoA should be scheduled for 3rd Sunday every month, instead of that  PoA scheduled for weekly Sunday.

**Comment by mrkarMSFT** [comment]
@rajakumarbabu - plz append MonthlyByWeekAndDay to the setting. 

<Parameter Name="WUFrequency" DefaultValue="MonthlyByWeekAndDay, 3, Sunday, 5:00:00" />

**Comment by mrkarMSFT** [comment]
@rajakumarbabu - plz append MonthlyByWeekAndDay. 

<Parameter Name="WUFrequency" DefaultValue="3,Sunday,5:00:00" />

**Comment by rajakumarbabu** [comment]
Thanks for the update, it works.
